In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("fredericobreno/play-tennis")

In [3]:
print(os.listdir(path))

['play_tennis.csv']

In [4]:
df = pd.read_csv(os.path.join(path,'play_tennis.csv'))

In [5]:
df.drop('day',axis=1, inplace=True)

In [6]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

# now applaying Naive Bias

### Creating LookUp Table

In [7]:
# calculating total 'yes' or 'no'
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [8]:
Pno = 5/14
Pyes = 9/14

In [9]:
# Outlook

pd.crosstab(df['outlook'], df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [10]:
Pon = 0
Prn = 2/5
Psn = 3/5

Poy = 4/9
Pry = 3/9
Psy = 2/9

In [11]:
# temp 

pd.crosstab(df['temp'], df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [12]:
Pcooln = 1/5
Photn = 2/5
Pmildn = 2/5

Pcooly = 3/9
Photy = 2/9
Pmildy = 4/9

In [13]:
# humidity	

pd.crosstab(df['humidity'], df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [14]:
Phighn = 4/5
Pnormaln = 1/5

Phighy = 3/9
Pnormal = 6/9

In [15]:
# wind 

pd.crosstab(df['wind'], df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [16]:
Pstrongn = 3/5
Pweakn = 2/5

Pstrongy = 3/9
Pweaky = 6/9

#### Naive bias

In [17]:
# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak

PoYes = Pyes * Psy * Photy * Phighy * Pweaky

PoNo = Pno * Psn * Photn * Phighn * Pweakn

print('Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak\n')
print('Probability of yes: ', PoYes)
print('Probability of No: ', PoNo)

Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak

Probability of yes:  0.007054673721340388
Probability of No:  0.02742857142857143